### ISSUE TITLE
nms

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#39]
https://github.com/ZakharovAleksey/yandex_cpp/blob/680e079385fc147918cf5340d055168140ff84bd/sprint_2/server_test.h#L10-L14
Оформление пространств имен
https://google.github.io/styleguide/cppguide.html#Namespace_Formatting

Т.е отступы не нужны - ни в .H ни в .CPP

**Comment by ZakharovAleksey** [comment]
Да, понял - сделал себе `.clang-format` файл отнаследованный от **google**.
Сейчас настройки такие (см. ниже) и если ест ьпожелания по форматированию - добавлю :)

```yaml
BasedOnStyle: Google
ColumnLimit: 120
IndentWidth: 4
AllowShortBlocksOnASingleLine: "Never"
AllowShortFunctionsOnASingleLine: "Empty"
AllowShortIfStatementsOnASingleLine: "Never"
AllowShortLoopsOnASingleLine: false
```

P.S. вроде добавление `.clang-format` файло разрешило проблемы с форматированием
